package com.pharmalink.medication_service.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import org.springframework.data.domain.Persistable;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * Moved from the monolith as-is, plus one addition: medicationGroupId.
 *
 * Fixes BACKEND_TODO.md's flagged gap — a "twice daily" medication used to
 * create 2 independent rows (one per reminder time) with no shared
 * identifier, so editing one never touched the other, and there was no way
 * to edit at all (only delete+recreate). medicationGroupId lets multiple
 * rows represent one logical medication: PUT /group/{medicationGroupId}
 * edits shared fields (name/dosage/instructions/dates) across every row in
 * the group, while PUT /{medicationId} still edits a single row (e.g. just
 * that dose's reminderTime). Defaults to the row's own id when not
 * explicitly grouped, so ungrouped medications are unaffected.
 */
@Entity
@Table(name = "medications", indexes = {
    @Index(name = "idx_medication_user",        columnList = "userId"),
    @Index(name = "idx_medication_user_status",  columnList = "userId, status"),
    @Index(name = "idx_medication_group",        columnList = "medicationGroupId")
})
// Added 2026-07-24 — real root cause of "Add Medication" failing with
// "Row was already updated or deleted by another transaction" on every
// single save, not intermittently. MedicationService.addMedication()
// explicitly assigns the id (medication.setId(UUID.randomUUID()...)) BEFORE
// calling medicationRepository.save(), so it can reuse that same id as the
// default medicationGroupId in one insert (see that method's javadoc).
// Spring Data JPA's default isNew() check for an entity with no @Version
// field just asks "is the @Id null?" — since the id is deliberately
// non-null here, save() decided this was an UPDATE (entityManager.merge())
// instead of an INSERT (persist()), Hibernate ran an UPDATE against a row
// that doesn't exist yet, 0 rows matched, and Hibernate's default
// Expectations check treats "an UPDATE that touched 0 rows" as an
// optimistic-locking failure — hence that exact error text, every time.
// Implementing Persistable<String> lets Spring Data ask the entity
// directly instead of guessing from the id: isNew defaults to true for a
// brand-new `new Medication()`, and @PostLoad flips it to false the moment
// this row is ever loaded back out of the database (findById, queries,
// etc.), so every other existing save() path (updateDoseStatus,
// updateMedication, etc. — all of which load-then-save an existing row)
// is completely unaffected.
public class Medication implements Persistable<String> {

    public enum Status     { ACTIVE, INACTIVE, COMPLETED }
    public enum DoseStatus { PENDING, TAKEN, SNOOZED, MISSED }

    // FIXED (2026-07-24, round 2) — implementing Persistable<String> (below)
    // fixed HOW Spring Data routed save(): it now correctly calls
    // entityManager.persist() instead of merge(). But @GeneratedValue here
    // was still telling HIBERNATE ITSELF that this id is supposed to be
    // generated by Hibernate at insert time (null going in). Since
    // MedicationService.addMedication() always assigns the id manually
    // BEFORE save() (needed to reuse it as medicationGroupId — see that
    // method's javadoc), Hibernate's own persist() implementation saw a
    // non-null id on an entity it never generated/loaded and concluded it
    // must be a DETACHED instance being persisted by mistake — hence
    // "Detached entity passed to persist," a completely different Hibernate
    // safety check than the one Persistable fixed. Since this id is ALWAYS
    // application-assigned (never once relies on Hibernate's generator),
    // @GeneratedValue was actively wrong here, not just unnecessary —
    // removing it, combined with Persistable<String> below telling Spring
    // Data this is a new row, is what actually makes a plain INSERT happen.
    @Id
    private String id;

    @Transient
    private boolean isNew = true;

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostLoad
    void markNotNew() {
        this.isNew = false;
    }

    @Column(nullable = false)
    private String userId;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String dosage;

    @Column(nullable = false)
    private String frequency;

    private String instructions;

    @Column(nullable = false, columnDefinition = "TIME")
    private LocalTime reminderTime;

    @Column(nullable = false)
    private LocalDate startDate;

    private LocalDate endDate;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status = Status.ACTIVE;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private DoseStatus doseStatus = DoseStatus.PENDING;

    @Column(nullable = false)
    private String medicationGroupId;

    @Column(updatable = false)
    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    public Medication() {}

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getDosage() { return dosage; }
    public void setDosage(String dosage) { this.dosage = dosage; }

    public String getFrequency() { return frequency; }
    public void setFrequency(String frequency) { this.frequency = frequency; }

    public String getInstructions() { return instructions; }
    public void setInstructions(String instructions) { this.instructions = instructions; }

    public LocalTime getReminderTime() { return reminderTime; }
    public void setReminderTime(LocalTime reminderTime) { this.reminderTime = reminderTime; }

    public LocalDate getStartDate() { return startDate; }
    public void setStartDate(LocalDate startDate) { this.startDate = startDate; }

    public LocalDate getEndDate() { return endDate; }
    public void setEndDate(LocalDate endDate) { this.endDate = endDate; }

    public Status getStatus() { return status; }
    public void setStatus(Status status) { this.status = status; }

    public DoseStatus getDoseStatus() { return doseStatus; }
    public void setDoseStatus(DoseStatus doseStatus) { this.doseStatus = doseStatus; }

    public String getMedicationGroupId() { return medicationGroupId; }
    public void setMedicationGroupId(String medicationGroupId) { this.medicationGroupId = medicationGroupId; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}
